import CLRSLean.Chapter_19.Section_19_1_Fibonacci_Heap_Model

#check CLRS.Chapter19.FibHeap.Valid
#check CLRS.Chapter19.FibHeap.Represents
#check CLRS.Chapter19.FibHeap.makeHeap_correct
#check CLRS.Chapter19.FibHeap.potential
#check CLRS.Chapter19.FibHeap.potential_makeHeap
#check CLRS.Chapter19.FibHeap.potential_nonneg
#check CLRS.Chapter19.FibHeap.minimum_correct
#check CLRS.Chapter19.FibHeap.minimum_none_iff
#check CLRS.Chapter19.FibHeap.insert_correct
#check CLRS.Chapter19.FibHeap.insert_mem_iff
#check CLRS.Chapter19.FibHeap.union_correct
#check CLRS.Chapter19.FibHeap.union_mem_iff
#check CLRS.Chapter19.FibHeap.extractMin_correct
#check CLRS.Chapter19.FibHeap.extractMin_mem_iff
#check CLRS.Chapter19.FibHeap.extractMin_none_iff
#check CLRS.Chapter19.FibHeap.decreaseKey_correct
#check CLRS.Chapter19.FibHeap.decreaseKey_mem_iff
#check CLRS.Chapter19.FibHeap.delete_correct
#check CLRS.Chapter19.FibHeap.delete_mem_iff
#check CLRS.Chapter19.FibHeap.heapPotential_telescope
#check CLRS.Chapter19.FibHeap.fibLowerBound
#check CLRS.Chapter19.FibHeap.fibLowerBound_step
#check CLRS.Chapter19.FibHeap.fibLowerBound_pos
#check CLRS.Chapter19.FibHeap.fibLowerBound_le_succ
#check CLRS.Chapter19.FibHeap.fibLowerBound_monotone
#check CLRS.Chapter19.FibHeap.degree_bound_log
