import CLRSLean.Chapter_17.Section_17_1_Amortized_Framework
import CLRSLean.Chapter_17.Section_17_2_Stack_And_Counter
import CLRSLean.Chapter_17.Section_17_4_Dynamic_Tables

#check CLRS.Chapter17.prefixCost
#check CLRS.Chapter17.prefixCostR
#check CLRS.Chapter17.aggregate_bound_of_prefix_bound
#check CLRS.Chapter17.AccountingTrace
#check CLRS.Chapter17.accounting_balance
#check CLRS.Chapter17.accounting_totalCost_eq_totalCharge_sub_delta
#check CLRS.Chapter17.accounting_totalCost_le_totalCharge
#check CLRS.Chapter17.PotentialTrace
#check CLRS.Chapter17.amortizedCost
#check CLRS.Chapter17.potential_totalCost_eq_totalAmortized_sub_delta
#check CLRS.Chapter17.potential_totalCost_le_totalAmortized
#check CLRS.Chapter17.multiPop
#check CLRS.Chapter17.multiPopCost
#check CLRS.Chapter17.multiPop_totalCost_le
#check CLRS.Chapter17.binaryCounterIncrement
#check CLRS.Chapter17.bitFlipsForIncrement
#check CLRS.Chapter17.binaryCounter_totalFlips_le
#check CLRS.Chapter17.DynamicTableState
#check CLRS.Chapter17.DynamicTableState.Valid
#check CLRS.Chapter17.dynamicPotential
#check CLRS.Chapter17.dynamicTableAmortizedCost
#check CLRS.Chapter17.dynamicTable_amortizedBound
