import CLRSLean.Chapter_20.Section_20_1_VEB_Universe
import CLRSLean.Chapter_20.Section_20_2_VEB_Tree

#check CLRS.Chapter20.VEB.high
#check CLRS.Chapter20.VEB.low
#check CLRS.Chapter20.VEB.index
#check CLRS.Chapter20.VEB.index_high_low
#check CLRS.Chapter20.VEB.high_index
#check CLRS.Chapter20.VEB.low_index
#check CLRS.Chapter20.VEB.index_lt
#check CLRS.Chapter20.VEB.high_lt
#check CLRS.Chapter20.VEB.low_lt
#check CLRS.Chapter20.VEB.Tree
#check CLRS.Chapter20.VEB.Represents
#check CLRS.Chapter20.VEB.member
#check CLRS.Chapter20.VEB.member_correct
#check CLRS.Chapter20.VEB.member_lt_univ
#check CLRS.Chapter20.VEB.minimum_correct
#check CLRS.Chapter20.VEB.minimum_lt_univ
#check CLRS.Chapter20.VEB.minimum_none_iff
#check CLRS.Chapter20.VEB.maximum_correct
#check CLRS.Chapter20.VEB.maximum_lt_univ
#check CLRS.Chapter20.VEB.maximum_none_iff
#check CLRS.Chapter20.VEB.successor_correct
#check CLRS.Chapter20.VEB.successor_lt_univ
#check CLRS.Chapter20.VEB.successor_none_iff
#check CLRS.Chapter20.VEB.predecessor_correct
#check CLRS.Chapter20.VEB.predecessor_lt_univ
#check CLRS.Chapter20.VEB.predecessor_none_iff
#check CLRS.Chapter20.VEB.insert_correct
#check CLRS.Chapter20.VEB.insert_member_iff
#check CLRS.Chapter20.VEB.insert_member_self
#check CLRS.Chapter20.VEB.insert_member_old
#check CLRS.Chapter20.VEB.insert_minimum_correct
#check CLRS.Chapter20.VEB.insert_minimum_none_iff
#check CLRS.Chapter20.VEB.insert_maximum_correct
#check CLRS.Chapter20.VEB.insert_maximum_none_iff
#check CLRS.Chapter20.VEB.insert_successor_correct
#check CLRS.Chapter20.VEB.insert_successor_none_iff
#check CLRS.Chapter20.VEB.insert_predecessor_correct
#check CLRS.Chapter20.VEB.insert_predecessor_none_iff
#check CLRS.Chapter20.VEB.delete_correct
#check CLRS.Chapter20.VEB.delete_member_iff
#check CLRS.Chapter20.VEB.delete_member_deleted_false
#check CLRS.Chapter20.VEB.delete_member_of_ne
#check CLRS.Chapter20.VEB.delete_minimum_correct
#check CLRS.Chapter20.VEB.delete_minimum_none_iff
#check CLRS.Chapter20.VEB.delete_maximum_correct
#check CLRS.Chapter20.VEB.delete_maximum_none_iff
#check CLRS.Chapter20.VEB.delete_successor_correct
#check CLRS.Chapter20.VEB.delete_successor_none_iff
#check CLRS.Chapter20.VEB.delete_predecessor_correct
#check CLRS.Chapter20.VEB.delete_predecessor_none_iff
#check CLRS.Chapter20.VEB.operationDepth
#check CLRS.Chapter20.VEB.operationDepth_zero
#check CLRS.Chapter20.VEB.operationDepth_succ
#check CLRS.Chapter20.VEB.operationDepth_linear
#check CLRS.Chapter20.VEB.operationDepth_monotone
#check CLRS.Chapter20.VEB.operationDepth_strict_mono
