import CLRSLean.Chapter_18.Section_18_1_B_Tree_Model
import CLRSLean.Chapter_18.Section_18_2_B_Tree_Insertion
import CLRSLean.Chapter_18.Section_18_3_B_Tree_Deletion

#check CLRS.Chapter18.BTree
#check CLRS.Chapter18.BTree.keysOf
#check CLRS.Chapter18.BTree.mem
#check CLRS.Chapter18.BTree.Valid
#check CLRS.Chapter18.BTree.search
#check CLRS.Chapter18.BTree.search_correct
#check CLRS.Chapter18.BTree.minKeys
#check CLRS.Chapter18.BTree.minKeys_zero
#check CLRS.Chapter18.BTree.minKeys_pos
#check CLRS.Chapter18.BTree.one_le_minKeys
#check CLRS.Chapter18.BTree.minKeys_lower_bound
#check CLRS.Chapter18.BTree.minKeys_succ
#check CLRS.Chapter18.BTree.minKeys_le_succ
#check CLRS.Chapter18.BTree.minKeys_monotone_height
#check CLRS.Chapter18.BTree.splitChild
#check CLRS.Chapter18.BTree.splitChild_preserves_model
#check CLRS.Chapter18.BTree.splitChild_valid
#check CLRS.Chapter18.BTree.splitChild_mem_iff
#check CLRS.Chapter18.BTree.splitChild_mem_old
#check CLRS.Chapter18.BTree.splitChild_not_mem_iff
#check CLRS.Chapter18.BTree.splitChild_search_iff
#check CLRS.Chapter18.BTree.splitChild_search_old
#check CLRS.Chapter18.BTree.splitChild_search_false_iff
#check CLRS.Chapter18.BTree.insert
#check CLRS.Chapter18.BTree.insert_preserves_model
#check CLRS.Chapter18.BTree.insert_mem_iff
#check CLRS.Chapter18.BTree.insert_search_iff
#check CLRS.Chapter18.BTree.insert_mem_self
#check CLRS.Chapter18.BTree.insert_search_self
#check CLRS.Chapter18.BTree.insert_mem_old
#check CLRS.Chapter18.BTree.insert_search_old
#check CLRS.Chapter18.BTree.insert_not_mem_iff
#check CLRS.Chapter18.BTree.insert_search_false_iff
#check CLRS.Chapter18.BTree.delete
#check CLRS.Chapter18.BTree.delete_preserves_model
#check CLRS.Chapter18.BTree.delete_mem_iff
#check CLRS.Chapter18.BTree.delete_search_iff
#check CLRS.Chapter18.BTree.delete_not_mem
#check CLRS.Chapter18.BTree.delete_search_deleted_false
#check CLRS.Chapter18.BTree.delete_mem_of_ne
#check CLRS.Chapter18.BTree.delete_search_of_ne
#check CLRS.Chapter18.BTree.delete_not_mem_iff
#check CLRS.Chapter18.BTree.delete_search_false_iff
