import CLRSLean.Chapter_20.Section_20_1_VEB_Universe
import CLRSLean.Chapter_20.Section_20_2_VEB_Tree

#check CLRS.Chapter20.VEB.high
#check CLRS.Chapter20.VEB.low
#check CLRS.Chapter20.VEB.index
#check CLRS.Chapter20.VEB.index_high_low
#check CLRS.Chapter20.VEB.high_index
#check CLRS.Chapter20.VEB.low_index
#check CLRS.Chapter20.VEB.index_lt
#check CLRS.Chapter20.VEB.high_lt
#check CLRS.Chapter20.VEB.low_lt
#check CLRS.Chapter20.VEB.Tree
#check CLRS.Chapter20.VEB.Represents
#check CLRS.Chapter20.VEB.member
#check CLRS.Chapter20.VEB.member_correct
#check CLRS.Chapter20.VEB.member_lt_univ
#check CLRS.Chapter20.VEB.minimum_correct
#check CLRS.Chapter20.VEB.minimum_mem
#check CLRS.Chapter20.VEB.minimum_le
#check CLRS.Chapter20.VEB.minimum_lt_univ
#check CLRS.Chapter20.VEB.minimum_none_iff
#check CLRS.Chapter20.VEB.minimum_none_of_empty
#check CLRS.Chapter20.VEB.minimum_ne_none_of_nonempty
#check CLRS.Chapter20.VEB.maximum_correct
#check CLRS.Chapter20.VEB.maximum_mem
#check CLRS.Chapter20.VEB.le_maximum
#check CLRS.Chapter20.VEB.maximum_lt_univ
#check CLRS.Chapter20.VEB.maximum_none_iff
#check CLRS.Chapter20.VEB.maximum_none_of_empty
#check CLRS.Chapter20.VEB.maximum_ne_none_of_nonempty
#check CLRS.Chapter20.VEB.successor_correct
#check CLRS.Chapter20.VEB.successor_mem
#check CLRS.Chapter20.VEB.successor_gt
#check CLRS.Chapter20.VEB.successor_le
#check CLRS.Chapter20.VEB.successor_lt_univ
#check CLRS.Chapter20.VEB.successor_none_iff
#check CLRS.Chapter20.VEB.successor_none_of_no_gt
#check CLRS.Chapter20.VEB.successor_ne_none_of_exists_gt
#check CLRS.Chapter20.VEB.predecessor_correct
#check CLRS.Chapter20.VEB.predecessor_mem
#check CLRS.Chapter20.VEB.predecessor_lt
#check CLRS.Chapter20.VEB.le_predecessor
#check CLRS.Chapter20.VEB.predecessor_lt_univ
#check CLRS.Chapter20.VEB.predecessor_none_iff
#check CLRS.Chapter20.VEB.predecessor_none_of_no_lt
#check CLRS.Chapter20.VEB.predecessor_ne_none_of_exists_lt
#check CLRS.Chapter20.VEB.insert_correct
#check CLRS.Chapter20.VEB.insert_member_iff
#check CLRS.Chapter20.VEB.insert_member_lt_univ
#check CLRS.Chapter20.VEB.insert_member_self
#check CLRS.Chapter20.VEB.insert_member_old
#check CLRS.Chapter20.VEB.insert_member_false_iff
#check CLRS.Chapter20.VEB.insert_member_false_of_ne
#check CLRS.Chapter20.VEB.insert_minimum_correct
#check CLRS.Chapter20.VEB.insert_minimum_mem
#check CLRS.Chapter20.VEB.insert_minimum_mem_old_of_ne
#check CLRS.Chapter20.VEB.insert_minimum_le_inserted
#check CLRS.Chapter20.VEB.insert_minimum_le_old
#check CLRS.Chapter20.VEB.insert_minimum_lt_univ
#check CLRS.Chapter20.VEB.insert_minimum_none_iff
#check CLRS.Chapter20.VEB.insert_minimum_ne_none
#check CLRS.Chapter20.VEB.insert_maximum_correct
#check CLRS.Chapter20.VEB.insert_maximum_mem
#check CLRS.Chapter20.VEB.insert_maximum_mem_old_of_ne
#check CLRS.Chapter20.VEB.insert_maximum_inserted_le
#check CLRS.Chapter20.VEB.insert_maximum_old_le
#check CLRS.Chapter20.VEB.insert_maximum_lt_univ
#check CLRS.Chapter20.VEB.insert_maximum_none_iff
#check CLRS.Chapter20.VEB.insert_maximum_ne_none
#check CLRS.Chapter20.VEB.insert_successor_correct
#check CLRS.Chapter20.VEB.insert_successor_mem
#check CLRS.Chapter20.VEB.insert_successor_mem_old_of_ne
#check CLRS.Chapter20.VEB.insert_successor_gt
#check CLRS.Chapter20.VEB.insert_successor_le
#check CLRS.Chapter20.VEB.insert_successor_lt_univ
#check CLRS.Chapter20.VEB.insert_successor_none_iff
#check CLRS.Chapter20.VEB.insert_successor_none_of_no_gt
#check CLRS.Chapter20.VEB.insert_successor_none_of_insert_le_old_no_gt
#check CLRS.Chapter20.VEB.insert_successor_ne_none_of_insert_gt
#check CLRS.Chapter20.VEB.insert_successor_ne_none_of_old_gt
#check CLRS.Chapter20.VEB.insert_predecessor_correct
#check CLRS.Chapter20.VEB.insert_predecessor_mem
#check CLRS.Chapter20.VEB.insert_predecessor_mem_old_of_ne
#check CLRS.Chapter20.VEB.insert_predecessor_lt
#check CLRS.Chapter20.VEB.insert_le_predecessor
#check CLRS.Chapter20.VEB.insert_predecessor_lt_univ
#check CLRS.Chapter20.VEB.insert_predecessor_none_iff
#check CLRS.Chapter20.VEB.insert_predecessor_none_of_no_lt
#check CLRS.Chapter20.VEB.insert_predecessor_none_of_query_le_insert_old_no_lt
#check CLRS.Chapter20.VEB.insert_predecessor_ne_none_of_insert_lt
#check CLRS.Chapter20.VEB.insert_predecessor_ne_none_of_old_lt
#check CLRS.Chapter20.VEB.delete_correct
#check CLRS.Chapter20.VEB.delete_member_iff
#check CLRS.Chapter20.VEB.delete_member_lt_univ
#check CLRS.Chapter20.VEB.delete_member_deleted_false
#check CLRS.Chapter20.VEB.delete_member_of_ne
#check CLRS.Chapter20.VEB.delete_member_false_iff
#check CLRS.Chapter20.VEB.delete_member_false_old
#check CLRS.Chapter20.VEB.delete_member_false_of_eq
#check CLRS.Chapter20.VEB.delete_minimum_correct
#check CLRS.Chapter20.VEB.delete_minimum_ne
#check CLRS.Chapter20.VEB.delete_minimum_mem
#check CLRS.Chapter20.VEB.delete_minimum_le_old
#check CLRS.Chapter20.VEB.delete_minimum_lt_univ
#check CLRS.Chapter20.VEB.delete_minimum_none_iff
#check CLRS.Chapter20.VEB.delete_minimum_none_of_all_eq
#check CLRS.Chapter20.VEB.delete_minimum_ne_none_of_remaining
#check CLRS.Chapter20.VEB.delete_maximum_correct
#check CLRS.Chapter20.VEB.delete_maximum_ne
#check CLRS.Chapter20.VEB.delete_maximum_mem
#check CLRS.Chapter20.VEB.delete_maximum_old_le
#check CLRS.Chapter20.VEB.delete_maximum_lt_univ
#check CLRS.Chapter20.VEB.delete_maximum_none_iff
#check CLRS.Chapter20.VEB.delete_maximum_none_of_all_eq
#check CLRS.Chapter20.VEB.delete_maximum_ne_none_of_remaining
#check CLRS.Chapter20.VEB.delete_successor_correct
#check CLRS.Chapter20.VEB.delete_successor_mem
#check CLRS.Chapter20.VEB.delete_successor_gt
#check CLRS.Chapter20.VEB.delete_successor_le
#check CLRS.Chapter20.VEB.delete_successor_lt_univ
#check CLRS.Chapter20.VEB.delete_successor_none_iff
#check CLRS.Chapter20.VEB.delete_successor_none_of_no_gt
#check CLRS.Chapter20.VEB.delete_successor_none_of_old_no_gt
#check CLRS.Chapter20.VEB.delete_successor_ne_none_of_remaining_gt
#check CLRS.Chapter20.VEB.delete_predecessor_correct
#check CLRS.Chapter20.VEB.delete_predecessor_mem
#check CLRS.Chapter20.VEB.delete_predecessor_lt
#check CLRS.Chapter20.VEB.delete_le_predecessor
#check CLRS.Chapter20.VEB.delete_predecessor_lt_univ
#check CLRS.Chapter20.VEB.delete_predecessor_none_iff
#check CLRS.Chapter20.VEB.delete_predecessor_none_of_no_lt
#check CLRS.Chapter20.VEB.delete_predecessor_none_of_old_no_lt
#check CLRS.Chapter20.VEB.delete_predecessor_ne_none_of_remaining_lt
#check CLRS.Chapter20.VEB.operationDepth
#check CLRS.Chapter20.VEB.operationDepth_zero
#check CLRS.Chapter20.VEB.operationDepth_succ
#check CLRS.Chapter20.VEB.operationDepth_linear
#check CLRS.Chapter20.VEB.operationDepth_monotone
#check CLRS.Chapter20.VEB.operationDepth_strict_mono
