import CLRSLean.Chapter_17.Section_17_1_Amortized_Framework
import CLRSLean.Chapter_17.Section_17_2_Stack_And_Counter
import CLRSLean.Chapter_17.Section_17_4_Dynamic_Tables

#check CLRS.Chapter17.prefixCost
#check CLRS.Chapter17.prefixCostR
#check CLRS.Chapter17.aggregate_bound_of_prefix_bound
#check CLRS.Chapter17.AccountingTrace
#check CLRS.Chapter17.accounting_balance
#check CLRS.Chapter17.accounting_totalCost_eq_totalCharge_sub_delta
#check CLRS.Chapter17.accounting_totalCost_le_totalCharge
#check CLRS.Chapter17.PotentialTrace
#check CLRS.Chapter17.amortizedCost
#check CLRS.Chapter17.potential_totalCost_eq_totalAmortized_sub_delta
#check CLRS.Chapter17.potential_totalCost_le_totalAmortized
#check CLRS.Chapter17.multiPop
#check CLRS.Chapter17.multiPopCost
#check CLRS.Chapter17.multiPop_totalCost_le
#check CLRS.Chapter17.binaryCounterIncrement
#check CLRS.Chapter17.trueBitCount
#check CLRS.Chapter17.bitFlipsOfIncrement
#check CLRS.Chapter17.binaryCounter_increment_potential_le_two
#check CLRS.Chapter17.binaryCounterAfter
#check CLRS.Chapter17.binaryCounterTraceFlips
#check CLRS.Chapter17.binaryCounter_trace_potential_le
#check CLRS.Chapter17.binaryCounter_trace_totalFlips_le
#check CLRS.Chapter17.bitFlipsForIncrement
#check CLRS.Chapter17.binaryCounter_totalFlips_le
#check CLRS.Chapter17.DynamicTableState
#check CLRS.Chapter17.DynamicTableState.Valid
#check CLRS.Chapter17.dynamicPotential
#check CLRS.Chapter17.dynamicPotential_nonneg
#check CLRS.Chapter17.dynamicTableAmortizedCost
#check CLRS.Chapter17.dynamicTableInsertSize
#check CLRS.Chapter17.dynamicTableInsert
#check CLRS.Chapter17.dynamicTableInsertCost
#check CLRS.Chapter17.dynamicTableInsertCost_le_num_succ
#check CLRS.Chapter17.dynamicTableInsertCost_of_fits
#check CLRS.Chapter17.dynamicTableInsertCost_of_expand
#check CLRS.Chapter17.dynamicTableInsertSize_fits
#check CLRS.Chapter17.dynamicTableInsertSize_ge_size
#check CLRS.Chapter17.dynamicTableInsert_valid
#check CLRS.Chapter17.dynamicTableInsert_num
#check CLRS.Chapter17.dynamicTableInsert_capacity_fits
#check CLRS.Chapter17.dynamicTableInsert_capacity_ge_size
#check CLRS.Chapter17.dynamicTableInsert_amortizedBound
#check CLRS.Chapter17.dynamicTableDeleteSize
#check CLRS.Chapter17.dynamicTableDelete
#check CLRS.Chapter17.dynamicTableDeleteCost
#check CLRS.Chapter17.dynamicTableDeleteCost_le_num
#check CLRS.Chapter17.dynamicTableDeleteCost_empty
#check CLRS.Chapter17.dynamicTableDeleteCost_of_contract
#check CLRS.Chapter17.dynamicTableDeleteCost_of_no_contract
#check CLRS.Chapter17.dynamicTableDeleteSize_fits
#check CLRS.Chapter17.dynamicTableDeleteSize_le_size
#check CLRS.Chapter17.dynamicTableDelete_valid
#check CLRS.Chapter17.dynamicTableDelete_num
#check CLRS.Chapter17.dynamicTableDelete_capacity_fits
#check CLRS.Chapter17.dynamicTableDelete_capacity_le_size
#check CLRS.Chapter17.dynamicTableDelete_amortizedBound
#check CLRS.Chapter17.dynamicTable_amortizedBound
